### ISSUE TITLE
Zebra striping is messed up by hiding comments

### ISSUE THREAD

**Issue by austindonisan** [btmccord/Mountain-Project-Beta-Videos#3]
Plucking comments out throws off the zebra striping.

![before](https://github.com/btmccord/Mountain-Project-Beta-Videos/assets/19476302/f4366e22-3adf-476e-8bcd-c2c107d5d6f0)

This can be easily fixed with "nth-child" which has broad support for almost 6+ months now. I'm not sure how extension CSS works, you might have to increase the priority of the selectors to override the existing MP rule of  `.comments .comments-body .comment-list table:nth-of-type(2n) {}`.

```
.comments .comments-body .comment-list table:nth-child(2n of :not(.mpbv-hidden)) {
  background-color: transparent;
}

.comments .comments-body .comment-list table:nth-child(2n + 1 of :not(.mpbv-hidden)) {
  background-color: #f2f2f2; 
}
```

Fixed:
![after](https://github.com/btmccord/Mountain-Project-Beta-Videos/assets/19476302/ec681721-6608-43bd-8149-8cbda3884994)

**Comment by btmccord** [comment]
Fixed in v1.3
